### ISSUE TITLE
Duo CLI support

### ISSUE THREAD

**Issue by jimsmith** [nathan-v/aws_okta_keyman#11]
Hello,

I note this 'In the case of Duo Auth a web page is opened (served locally) for the user to interact with Duo and select their preferred authentication method. Once Duo is successful the user may close the browser or tab.'

How will this work for end user that just has No X11 support and just a plain linux SSH terminal ?

Would this help ? (I'm by no means a s/w developer but seems this has it working - haven't used it myself though)
https://github.com/segmentio/aws-okta/blob/master/lib/duo.go#L52-L55

Thanks.

**Comment by nathan-v** [comment]
Hi, @jimsmith!

    Duo does support CLI only but Okta is who calls Duo for you. Unfortunately Okta does not support triggering Duo Push directly at this time. I have a feature request open with them for that but haven't gotten a response yet. Until Okta supports triggering Duo Push directly there's not a good solution other than displaying the Duo Web interface to the user.

    If I can find a way to get around it I will definitely make the change as soon as I can to get rid of the web browser requirement.

**Comment by nathan-v** [comment]
I did find a package that seems to be faking the web portion so I'll look into it when I have some time.

https://github.com/segmentio/aws-okta/blob/master/lib/duo.go

**Comment by nathan-v** [comment]
@jimsmith & @seb-steuer,  I have this functionality working on my local branch for Duo Push. I hope to have it actually complete, clean, and ready for use soon.

**Comment by nathan-v** [comment]
For the moment I'm going to support Duo Push only but it looks like passcode and call options are possible as well so I'll leave this issue open after the initial feature to see if I can get those added as well.

https://github.com/Versent/saml2aws/blob/master/pkg/provider/shibboleth/shibboleth.go#L221

**Comment by nathan-v** [comment]
Change in master and updated package is on Pypi.
