### ISSUE TITLE
Failed Okta/Duo configuration

### ISSUE THREAD

**Issue by jpippin** [nathan-v/aws_okta_keyman#15]
Hello and thank you for this project.

I think I might have an issue with my configuration, but I'm not sure where at.

Configuration:
Linux desktop
AWS with Okta and Duo MFA.

It appears that my username and password is working (output modified), but the duo portion isn't being called.  The command isn't launching the browser window.

$ cat /home/username/.config/aws_okta_keyman.yml
accounts:
- appid: abcdefghijklmnopqrst/012
  name: account
org: example
reup: 0
username: username

$ aws_okta_keyman -a abcdefghijklmnopqrst/012 -o example -u username -c /home/username/.config/aws_okta_keyman.yml                                            
14:08:42   (INFO) AWS Okta Keyman v0.4.0
Password: 
14:08:55   (INFO) Successfully authed User Name
14:08:55   (INFO) Getting SAML Assertion from example
14:08:55   (ERROR) Could not find any Role in the SAML assertion
14:08:55   (ERROR) {'assertion': b''}
14:08:55   (ERROR) AWS SAML response invalid. Retrying...
14:08:56   (INFO) Getting SAML Assertion from example
14:08:56   (ERROR) Could not find any Role in the SAML assertion
14:08:56   (ERROR) {'assertion': b''}
14:08:56   (ERROR) AWS SAML response invalid. Retrying...
14:08:57   (INFO) Getting SAML Assertion from example
14:08:57   (ERROR) Could not find any Role in the SAML assertion
14:08:57   (ERROR) {'assertion': b''}
14:08:57   (ERROR) AWS SAML response invalid. Retrying...
14:08:58   (CRITICAL) SAML failure. Please reauthenticate.

If you can assist that would be great.  Thank you for any input.

Joe

**Comment by nathan-v** [comment]
> 14:08:55 (INFO) Successfully authed User Name

Authenticating to Okta is definitely working.

> 14:08:55 (ERROR) Could not find any Role in the SAML assertion

Looks like a configuration issue on the Okta side.

You could also run with debug but keep in mind the output _will contain sensitive information_ so check in case that's helpful for your own debugging without sharing the output.

**Comment by jpippin** [comment]
I apologize for the late response.  Thank you for the information.  I'll check with the okta side and let you know what I find out.

Joe

**Comment by jpippin** [comment]
So if we disable 2FA (DUO) in okta, it works.  When we are using 2FA, which is DUO, it doesn't work.  It isn't launching the DUO piece from what it looks like to me.  Perhaps, the response from okta isn't what the keyman app is expecting?  The output from the debug mode returns from what it looks like, is just the okta login page.
[linux-desktop-cli-output.txt](https://github.com/nathan-v/aws_okta_keyman/files/2318824/linux-desktop-cli-output.txt)

**Comment by bazimov** [comment]
I am seeing the same error too for duo. @jpippin did you find any solution for duo mfa?

**Comment by jpippin** [comment]
I did actually.  I apologize for not posting here.  We are able to use the Okta/DUO/cli now.  We are using the directions at this link.  [https://github.com/oktadeveloper/okta-aws-cli-assume-role](https://github.com/oktadeveloper/okta-aws-cli-assume-role)  We 

Update the .okta/config.properties file...
`OKTA_ORG=<your site>.okta.com
OKTA_AWS_APP_URL=https://arccorp.okta.com/home/amazon_aws/<Your site info>
OKTA_USERNAME=username
OKTA_PASSWORD=
OKTA_BROWSER_AUTH=true`

There appears to be a bug with the 2.0.2 jar file though.  I've had to stick with the 2.0.0 jar file with the version of java I'm using.  I haven't got the 2.0.2 jar file working yet.  So your mileage may vary.

**Comment by bazimov** [comment]
@jpippin So you ended up not using this aws_okta_keyman tool but okta-aws-cli-assume-role tool? 

This aws_okta_keyman really fits for our use case, where we apply terraform changes too with aws profiles. We need these api keys in aws profiles.

**Comment by bazimov** [comment]
> Looks like a configuration issue on the Okta side.

@nathan-v Do you happen to have working configuration for duo? I have just enabled duo as mfa to aws app then marked require duo once a day. I wonder if it needs to be certain way for this to work?

**Comment by nathan-v** [comment]
Hey @bazimov, I was using this successfully with Duo at work but have not been using it lately due to some changes at work. I'll be back to working on this project and addressing issues hopefully soon.

@opragel were you using Duo at all? I can't remember if you had been or not but I know you had this deployed out to the engineering team.

**Comment by bazimov** [comment]
@nathan-v Thanks for your reply! Have you used Duo on OKTA main page for MFA or was it on application level? I am trying on application level, I have MFA enforced only for AWS app.

**Comment by nathan-v** [comment]
@bazimov IIRC it was at the main page not at the application.

**Comment by bazimov** [comment]
Thanks, it worked with ORG level MFA! 🎉

**Comment by nathan-v** [comment]
Looks like the OP moved to another tool and the only other issue mentioned here has been resolved. Closing.
