### ISSUE TITLE
Support AWS Role as config/command line option

### ISSUE THREAD

**Issue by jmonson** [nathan-v/aws_okta_keyman#56]
**Is your feature request related to a problem? Please describe.**
I would like to streamline use such that a default role could be set and avoid the role selection menu.

**Describe the solution you'd like**
Allow `--role` input parameter. Perhaps since there can be multiple accounts, input could be [Account ID]:[Role Name]. In addition, allow setting this in the configuration. If the arg / config is set, the role will be automatically selected without prompting to select a role. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by nathan-v** [comment]
Definitely something I'd like to add at some point. I'd like to be able to match on account+role or just role and let you pick the account if multiple role matches. It would definitely speed up my own workflow at times.

**Comment by ramsperger** [comment]
Woot. Thanks for merging!
