### ISSUE TITLE
Duo Web Failing

### ISSUE THREAD

**Issue by radsec** [nathan-v/aws_okta_keyman#64]
Duo web portal is opening but 403 errors after approving a factor. The desired behavior works correctly with Duo push as the provided parameter.

`
aws_okta_keyman -o XXX -u ryan@XXXX -d web -D
10:59:34 (INFO) AWS Okta Keyman 🔐 v0.8.1
Password:
10:59:36 (DEBUG) Base URL Set to: https://XXX.okta.com
10:59:36 (DEBUG) Attempting to authenticate to Okta
10:59:36 (DEBUG) Starting new HTTPS connection (1): XXX.okta.com:443

10:59:36 (DEBUG) https://XXX.okta.com:443 "POST /api/v1/authn HTTP/1.1" 200 None

10:59:36 (DEBUG) {'stateToken': '00-XXX', 'expiresAt': '2020-04-29T18:04:36.000Z', 'status': 'MFA_REQUIRED', '_embedded': {'user': {'id': 'XXX'', 'passwordChanged': '2020-04-29T01:04:15.000Z', 'profile': {'login': 'ryan@XXX', 'firstName': 'Ryan', 'lastName': 'XXX', 'locale': 'en', 'timeZone': 'America/Los_Angeles'}}, 'factors': [{'id': 'XXX', 'factorType': 'web', 'provider': 'DUO', 'vendorName': 'DUO', 'profile': {'credentialId': 'ryan@XXX'}, '_links': {'verify': {'href': 'https://XXX.okta.com/api/v1/authn/factors/XXX/verify', 'hints': {'allow': ['POST']}}}}], 'policy': {'allowRememberDevice': True, 'rememberDeviceLifetimeInMinutes': 15, 'rememberDeviceByDefault': False, 'factorsPolicyInfo': {}}}, '_links': {'cancel': {'href': 'https://XXX.okta.com/api/v1/authn/cancel', 'hints': {'allow': ['POST']}}}}

10:59:36 (DEBUG) Duo Auth factor found
10:59:36 (DEBUG) Duo Auth factor found
10:59:36 (DEBUG) https://XXX.okta.com:443 "POST /api/v1/authn/factors/XXX/verify HTTP/1.1" 200 None

10:59:36 (DEBUG) {'stateToken': 'XXX', 'expiresAt': '2020-04-29T18:04:36.000Z', 'status': 'MFA_CHALLENGE', 'factorResult': 'WAITING', '_embedded': {'user': {'id': 'XXX', 'passwordChanged': '2020-04-29T01:04:15.000Z', 'profile': {'login': 'ryan@XXX', 'firstName': 'Ryan', 'lastName': 'XXX', 'locale': 'en', 'timeZone': 'America/Los_Angeles'}}, 'factor': {'id': 'XXX', 'factorType': 'web', 'provider': 'DUO', 'vendorName': 'DUO', 'profile': {'credentialId': 'ryan@XXXX'}, '_embedded': {'verification': {'host': 'api-XXX.duosecurity.com', 'signature': 'XXX', 'factorResult': 'WAITING', '_links': {'complete': {'href': 'https://XXX.okta.com/api/v1/authn/factors/XXX/lifecycle/duoCallback', 'hints': {'allow': ['POST']}}, 'script': {'href': 'https://XXX.okta.com/js/sections/duo/Duo-Web-v2.6.js', 'type': 'text/javascript; charset=utf-8'}}}}}, 'policy': {'allowRememberDevice': True, 'rememberDeviceLifetimeInMinutes': 15, 'rememberDeviceByDefault': False, 'factorsPolicyInfo': {}}}, '_links': {'next': {'name': 'poll', 'href': 'https://XXX.okta.com/api/v1/authn/factors/XXX/verify', 'hints': {'allow': ['POST']}}, 'prev': {'href': 'https://XXX.okta.com/api/v1/authn/previous', 'hints': {'allow': ['POST']}}, 'cancel': {'href': 'https://XXX.okta.com/api/v1/authn/cancel', 'hints': {'allow': ['POST']}}}}

10:59:36 (WARNING) Duo required; opening browser...

10:59:39 (DEBUG) https://XXX.okta.com:443 "GET /api/v1/users/me/appLinks HTTP/1.1" 403 None

10:59:39 (CRITICAL) 😬 Unhandled exception: 403 Client Error: Forbidden for url: https://XXX.okta.com/api/v1/users/me/appLinks

10:59:39 (DEBUG) Traceback (most recent call last):
  File "/usr/local/Cellar/aws_okta_keyman/0.8.1/libexec/lib/python3.7/site-packages/aws_okta_keyman/keyman.py", line 83, in main
    self.handle_appid_selection(okta_ready=True)
  File "/usr/local/Cellar/aws_okta_keyman/0.8.1/libexec/lib/python3.7/site-packages/aws_okta_keyman/keyman.py", line 272, in handle_appid_selection
    self.config.accounts = self.okta_client.get_aws_apps()
  File "/usr/local/Cellar/aws_okta_keyman/0.8.1/libexec/lib/python3.7/site-packages/aws_okta_keyman/okta.py", line 547, in get_aws_apps
    resp.raise_for_status()
  File "/usr/local/Cellar/aws_okta_keyman/0.8.1/libexec/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://XXX.okta.com/api/v1/users/me/appLinks
`

**Comment by nathanveenkersonos** [comment]
Hey, @radsec. I'll see if there's anything I can sort out on this but unfortunately I don't have an Okta+Duo environment to test against any longer.

Pretty much all of the Duo support is a hack of some kind or another because of how Duo works so it's not a big surprise that it broke unfortunately.

**Comment by nathan-v** [comment]
I don't have an Okta/Duo setup to test against any longer but I'll see if there's anything I can find out here. If anyone else has some insight on this I'd appreciate it.

**Comment by nathan-v** [comment]
This has been fixed locally and will be released with 0.9.0 @radsec  :)
