### ISSUE TITLE
Add the ability to specify an Okta region 

### ISSUE THREAD

**Issue by supersee** [nathan-v/aws_okta_keyman#65]
**Is your feature request related to a problem? Please describe.**
Our current okta instance runs in the okta-emea region and the default region is hardcoded to okta.com

**Describe the solution you'd like**
Make the region location a param 

**Describe alternatives you've considered**
Manually edited the code after install to point to our region

**Additional context**
The line below needs to be dynamic as to include the region.
https://github.com/nathan-v/aws_okta_keyman/blob/master/aws_okta_keyman/okta.py#L36

I will submit a pull request for this as soon as I can , this ticket is just to make the author and anyone else using the library aware of the limitation.

**Comment by nathan-v** [comment]
Support for using the full Okta org url will be in the next update.

**Comment by nathan-v** [comment]
Done in #98.
