### ISSUE TITLE
Critical Unknown Error

### ISSUE THREAD

**Issue by jpbarto** [nathan-v/aws_okta_keyman#66]
**Describe the bug**

**To Reproduce**
1. Authenticate to Okta which is configured to assume multiple roles in multiple accounts
2. Use Authy MFA
3. use command: 
aws_okta_keyman -u 'user.joe@gmail.com' -D -a '0oadw4gu5tQ461r5a356' -s -o userjoeorg

**Expected behavior**
Expect to be presented with a list of account / role pairs which can be assumed.

**Screenshots**
Output:
22:08:26 (INFO) Successfully authed User Joe
22:08:26 (DEBUG) Long-lived token needed; requesting Okta API token
22:08:27 (DEBUG) https://userjoeorg.okta.com:443 "POST /api/v1/sessions HTTP/1.1" 200 None
22:08:27 (DEBUG) {'id': '102ruak3DEyTrA4Sw5L5yw53Q', 'userId': '00udsa7ad720P5iei356', 'login': 'user.joe@gmail.com', 'createdAt': '2020-06-08T22:08:17.000Z', 'expiresAt': '2020-06-09T00:08:17.000Z', 'status': 'ACTIVE', 'lastPasswordVerification': '2020-06-08T22:08:17.000Z', 'lastFactorVerification': '2020-06-08T22:08:26.000Z', 'amr': ['otp', 'mfa', 'pwd'], 'idp': {'id': '00odaabcdj8ypc7wE356', 'type': 'OKTA'}, 'mfaActive': True, '_links': {'self': {'href': 'https://userjoeorg.okta.com/api/v1/sessions/me', 'hints': {'allow': ['GET', 'DELETE']}}, 'refresh': {'href': 'https://userjoeorg.okta.com/api/v1/sessions/me/lifecycle/refresh', 'hints': {'allow': ['POST']}}, 'user': {'name': 'User Joe', 'href': 'https://userjoeorg.okta.com/api/v1/users/me', 'hints': {'allow': ['GET']}}}}
22:08:27 (INFO) Getting SAML Assertion from userjoeorg
22:08:27 (DEBUG) https://userjoeorg.okta.com:443 "GET /home/amazon_aws/0oadwn0g5tQ461r5a356 HTTP/1.1" 200 None
22:08:27 (CRITICAL) Unknown error
22:08:27 (ERROR) API response invalid. Retrying...
22:08:28 (INFO) Getting SAML Assertion from userjoeorg
22:08:28 (DEBUG) https://userjoeorg.okta.com:443 "GET /home/amazon_aws/0oadw4hj5tQ461r5a356 HTTP/1.1" 200 None
22:08:28 (CRITICAL) Unknown error
22:08:28 (ERROR) API response invalid. Retrying...
22:08:29 (INFO) Getting SAML Assertion from userjoeorg
22:08:29 (DEBUG) https://userjoeorg.okta.com:443 "GET /home/amazon_aws/0oadwn0g5tQ461r5a356 HTTP/1.1" 200 None
22:08:29 (CRITICAL) Unknown error
22:08:29 (ERROR) API response invalid. Retrying...
22:08:30 (CRITICAL) SAML failure. Please reauthenticate.

**Host (please complete the following information):**
 - Version [e.g. 0.5.0]
 - Python version [e.g. 3.5.0]

**Additional context**

**Comment by nathan-v** [comment]
Hi @jpbarto. This looks like it could be an issue with the AWS/Okta config. I'm not experiencing this issue in any of my environments at this time.

How is the integration configured?

**Comment by nathan-v** [comment]
Closing due to no response.
