### ISSUE TITLE
Unable to get aws_okta_keyman 0.8.1 working on mac

### ISSUE THREAD

**Issue by au78** [nathan-v/aws_okta_keyman#68]
**Describe the bug**
When I run aws_okta_keyman on my mac, I see the following error

09:25:30 (INFO) AWS Okta Keyman 🔐 v0.8.1
Traceback (most recent call last):
  File "/Users/$HOME.upadhyay/.pyenv/versions/3.7.3/bin/aws_okta_keyman", line 8, in <module>
    sys.exit(entry_point())
  File "/Users/$HOME.upadhyay/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aws_okta_keyman/main.py", line 28, in entry_point
    keyman = Keyman(sys.argv)
  File "/Users/$HOME.upadhyay/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aws_okta_keyman/keyman.py", line 57, in __init__
    self.config.get_config()
  File "/Users/$HOME.upadhyay/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aws_okta_keyman/config.py", line 119, in get_config
    self.parse_config(config_file)
  File "/Users/$HOME.upadhyay/.pyenv/versions/3.7.3/lib/python3.7/site-packages/aws_okta_keyman/config.py", line 321, in parse_config
    if not getattr(self, key):  # Only overwrite None not args
AttributeError: 'Config' object has no attribute 'rolealiases'

I am able to run `aws_okta_keyman config` and it generates the YAML... something like this:
`
accounts:
- appid: myAppId/123
  name: dev
console: null
duo_factor: null
duration: null
org: offerup
password_cache: null
region: null
reup: null
rolealiases:
- alias: prod
  role: 1231424:role/some_name_prod
- alias: dev
  role: 343131:role/some_name_dev
screen: null
username: my.email@address.com
`

**To Reproduce**
Install v0.8.1 of aws-okta-keyman. Thats the latest at the time of opening this bug. I used the following command
pip3 install --force aws_okta_keyman. I also tried uninstalling and then reinstalling. I get the same error upon running.

**Expected behavior**
`aws_okta_keyman -r` must work, asking for credentials etc.
Looks like some dependency is not compatible.

**Host (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Python version 2.7.18 and also tried with 3.7.3 and 3.7.7

**Additional context**
Installation log:
pip3 install --force aws_okta_keyman
Collecting aws_okta_keyman
  Using cached aws_okta_keyman-0.8.1.tar.gz (60 kB)
Collecting beautifulsoup4>=4.4.0
  Using cached beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
Collecting colorlog>=4.0.0
  Using cached colorlog-4.1.0-py2.py3-none-any.whl (14 kB)
Collecting requests>=2.10.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting boto3>=1.4.0
  Using cached boto3-1.14.20-py2.py3-none-any.whl (128 kB)
Collecting future>=0.16.0
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting configparser>=3.5.0
  Using cached configparser-5.0.0-py3-none-any.whl (22 kB)
Collecting PyYAML>=5.0
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting keyring>=18.0.0
  Using cached keyring-21.2.1-py3-none-any.whl (31 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.0.1-py3-none-any.whl (32 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting s3transfer<0.4.0,>=0.3.0
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
Collecting botocore<1.18.0,>=1.17.20
  Using cached botocore-1.17.20-py2.py3-none-any.whl (6.3 MB)
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: aws-okta-keyman, future, PyYAML
  Building wheel for aws-okta-keyman (setup.py) ... done
  Created wheel for aws-okta-keyman: filename=aws_okta_keyman-0.8.1-py3-none-any.whl size=63577 sha256=e583c1c80b4802e05f33369960b27416235ce7e581b781dd28705264b615ccff
  Stored in directory: $HOME/Library/Caches/pip/wheels/55/ed/82/8e0b051ccc0c65f00dc57a95f198b70d73057dd70fb55fba53
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=d8bbcda52cb09c9540d838981fce7b953a22c3d1fd3d416aff7f29ade8a82573
  Stored in directory: $HOME/Library/Caches/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp37-cp37m-macosx_10_15_x86_64.whl size=44627 sha256=6dd671b07d4ef1e3611e82fe0af7b9655ba482a15a9ef767d65fd91729769d70
  Stored in directory: $HOME/Library/Caches/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
Successfully built aws-okta-keyman future PyYAML
Installing collected packages: soupsieve, beautifulsoup4, colorlog, certifi, chardet, urllib3, idna, requests, jmespath, six, python-dateutil, docutils, botocore, s3transfer, boto3, future, configparser, PyYAML, zipp, importlib-metadata, keyring, aws-okta-keyman
  Attempting uninstall: soupsieve
    Found existing installation: soupsieve 2.0.1
    Uninstalling soupsieve-2.0.1:
      Successfully uninstalled soupsieve-2.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.9.1
    Uninstalling beautifulsoup4-4.9.1:
      Successfully uninstalled beautifulsoup4-4.9.1
  Attempting uninstall: colorlog
    Found existing installation: colorlog 4.1.0
    Uninstalling colorlog-4.1.0:
      Successfully uninstalled colorlog-4.1.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.6.20
    Uninstalling certifi-2020.6.20:
      Successfully uninstalled certifi-2020.6.20
  Attempting uninstall: chardet
    Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.9
    Uninstalling urllib3-1.25.9:
      Successfully uninstalled urllib3-1.25.9
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
  Attempting uninstall: jmespath
    Found existing installation: jmespath 0.10.0
    Uninstalling jmespath-0.10.0:
      Successfully uninstalled jmespath-0.10.0
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Uninstalling python-dateutil-2.8.1:
      Successfully uninstalled python-dateutil-2.8.1
  Attempting uninstall: docutils
    Found existing installation: docutils 0.15.2
    Uninstalling docutils-0.15.2:
      Successfully uninstalled docutils-0.15.2
  Attempting uninstall: botocore
    Found existing installation: botocore 1.17.20
    Uninstalling botocore-1.17.20:
      Successfully uninstalled botocore-1.17.20
  Attempting uninstall: s3transfer
    Found existing installation: s3transfer 0.3.3
    Uninstalling s3transfer-0.3.3:
      Successfully uninstalled s3transfer-0.3.3
  Attempting uninstall: boto3
    Found existing installation: boto3 1.14.20
    Uninstalling boto3-1.14.20:
      Successfully uninstalled boto3-1.14.20
  Attempting uninstall: future
    Found existing installation: future 0.18.2
    Uninstalling future-0.18.2:
      Successfully uninstalled future-0.18.2
  Attempting uninstall: configparser
    Found existing installation: configparser 5.0.0
    Uninstalling configparser-5.0.0:
      Successfully uninstalled configparser-5.0.0
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3.1
    Uninstalling PyYAML-5.3.1:
      Successfully uninstalled PyYAML-5.3.1
  Attempting uninstall: zipp
    Found existing installation: zipp 3.1.0
    Uninstalling zipp-3.1.0:
      Successfully uninstalled zipp-3.1.0
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 1.7.0
    Uninstalling importlib-metadata-1.7.0:
      Successfully uninstalled importlib-metadata-1.7.0
  Attempting uninstall: keyring
    Found existing installation: keyring 21.2.1
    Uninstalling keyring-21.2.1:
      Successfully uninstalled keyring-21.2.1
  Attempting uninstall: aws-okta-keyman
    Found existing installation: aws-okta-keyman 0.8.1
    Uninstalling aws-okta-keyman-0.8.1:
      Successfully uninstalled aws-okta-keyman-0.8.1
Successfully installed PyYAML-5.3.1 aws-okta-keyman-0.8.1 beautifulsoup4-4.9.1 boto3-1.14.20 botocore-1.17.20 certifi-2020.6.20 chardet-3.0.4 colorlog-4.1.0 configparser-5.0.0 docutils-0.15.2 future-0.18.2 idna-2.10 importlib-metadata-1.7.0 jmespath-0.10.0 keyring-21.2.1 python-dateutil-2.8.1 requests-2.24.0 s3transfer-0.3.3 six-1.15.0 soupsieve-2.0.1 urllib3-1.25.9 zipp-3.1.0

**Comment by au78** [comment]
Another update... if I delete my config file and use command line options directly then it works. So, it appears like, for some reason, the config file is not being parsed correctly. Not sure if there is some dependency issue or what...

**Comment by nathan-v** [comment]
Hi @au78, there is no role or alias feature in Keyman at this time. You appear to be using a fork.

**Comment by au78** [comment]
> Hi @au78, there is no role or alias feature in Keyman at this time. You appear to be using a fork.

I installed using the following command... is that not the right way to install?

`pip3 install --force aws_okta_keyman`

if not then what is the right way to get it?

Also... can you share a sample YAML file format? or guide me on how I can get it myself?

**Comment by nathan-v** [comment]
>Using cached aws_okta_keyman-0.8.1.tar.gz (60 kB)

Did you previously pull a different version? Your install is using a cached copy not pulling the file from Pypi.

There's an example YAML in the README.md

**Comment by au78** [comment]
I was trying multiple options... and each time i was installed as per the instructions on PyPi... so, yes... its possible that this time it picked up from the cache... but it it is not from any other place.

If there is something else I can do to show you that I did not have any cached version while installing then let me know. I will give it a shot...

After much struggle I was able to run this without using the YAML config... just FYI...

**Comment by au78** [comment]
Another update... I tried by setting up my config again... based on the sample given the README.md... I was able to successfully run keyman... 

I believe that this is not a bug as you rightly pointed out... Looks like I originally had some other other fork which somehow stopped working and I had no clue that it was different than this one... 

I will close this "issue"... Thank you @nathan-v for taking time to look at this...
