### ISSUE TITLE
Role Selection In Windows

### ISSUE THREAD

**Issue by RishabhGuptaIn** [nathan-v/aws_okta_keyman#71]
I've attached the response i've received while choosing a role, the issue in this is it picks the wrong role  , in the below output i chooses role 2 which is ideally **aws-exp-exp3** but it assumed the different one please check

12:56:37 (INFO) AWS Okta Keyman 🔐 v0.8.3
Password:
12:56:45 (WARNING) Okta Verify Push being sent...
12:56:45 (INFO) Waiting for MFA success...
12:56:48 (INFO) Waiting for MFA success...
12:56:50 (INFO) Successfully authed Rishabh Ag
12:56:51 (INFO) Getting SAML Assertion from example
12:56:51 (WARNING) Application-level MFA present; re-authenticating Okta
12:56:52 (WARNING) Okta Verify Push being sent...
12:56:52 (INFO) Waiting for MFA success...
12:56:55 (INFO) Waiting for MFA success...
12:56:57 (INFO) Getting SAML Assertion from example
12:56:59 (INFO) Starting AWS session for us-east-1
12:56:59 (WARNING) Multiple AWS roles found; please select one

    Account       Role
[0] 123456789009  aws-exp-exp1
[1] 123456789009  aws-exp-exp2
[2] 123456789009  aws-exp-exp3
Selection: 2

12:57:02 (INFO) Assuming role: arn:aws:iam::123456789009:role/aws-exp-exp2
12:57:04 (INFO) Wrote profile "default" to C:\Users\Rishabh/.aws\credentials 💾
12:57:04 (INFO) Current time is 2020-07-15 07:27:04.316262
12:57:04 (INFO) Session expires at 2020-07-15 08:27:03+00:00 ⏳
12:57:04 (INFO) All done! 👍

**Comment by nathan-v** [comment]
Likely related to the changes from @ramsperger. Looking into this.

**Comment by ramsperger** [comment]
Hmm. Yeah, that seems related to my stuff. I'll look when I get a chance if you don't get to it.

**Comment by nathan-v** [comment]
Well this isn't an off-by-one. It's inconsistent because if you select the first or last in a longer list it's not failing by being +/- 1 so it seems to be something is inconsistent between the list you're selecting from and the list being used to actually make the call to AWS.

**Comment by ramsperger** [comment]
Ahh! I think this may be from sorting after applying the index tracking in aws.py::available_roles then using the position rather than the index in assume_role.

I moved the list index assignment to after the sorting in:
https://github.com/nathan-v/aws_okta_keyman/pull/72

Alternatively, we could go through and find the role by roleIdx (and ignore the sort order).

I'm not 100% sure this is the issue at hand. The accounts I have access to all come back in order...

**Comment by nathan-v** [comment]
This is fixed and the updated version is released in 0.8.4.
