### ISSUE TITLE
429 Client Error Too Many requests for okta url.

### ISSUE THREAD

**Issue by jdispiritoae** [nathan-v/aws_okta_keyman#75]
**Describe the bug**
When using aws_okta_keyman and Okta SMS as the MFA, we get:
Unhandled exception: 429 Client Error: Too Many Requests for url: https://XXXXX.okta.com/api/v1/authn/factors/smscXXXX/verify

**To Reproduce**
1. run aws_okta_keyman -n PROFILENAME while Okta is configured to use SMS for MFA
2. enter password
3. enter first MFA
4. upon getting application level MFA the error comes up.

**Expected behavior**
aws_okta_keyman should get the credentials and write them to the credentials file

**ERROR Output**
14:03:06 (INFO) AWS Okta Keyman 🔐 v0.8.4
14:03:06 (INFO) Using account: aws /123/456
Password:
14:03:17 (WARNING) Okta SMS being requested...
14:03:17 (WARNING) MFA Requirement Detected - Enter your SMS (+1 XXX-XXX-9413) code here
MFA Passcode: 929468
14:03:32 (INFO) Successfully authed John Smith
14:03:32 (INFO) Getting SAML Assertion from xxxxxxx
14:03:32 (WARNING) Application-level MFA present; re-authenticating Okta
14:03:33 (WARNING) Okta SMS being requested...
14:03:33 (CRITICAL) 😬 Unhandled exception: 429 Client Error: Too Many Requests for url: https://XXXXX.okta.com/api/v1/authn/factors/smscXXXX/verify

**Host (please complete the following information):**
 - OS: Windows 10
 - Version 
 - Python version 3.7

**Additional context**
Is it possible for us to only have a single MFA challenge, instead of two?

**Comment by nathan-v** [comment]
I'll see if I can find a way to test this. Okta push and push works fine. SMS and SMS should also.

As for your question; the double-MFA is your Okta configuration. You have Okta login MFA enforced as well as MFA enforcement on the AWS integration. You would have to disable one or the other to have just a single MFA prompt.

**Comment by nathan-v** [comment]
Unable to repro and no followup from opener. Closing.
