### ISSUE TITLE
Rename project to something like aws_okta_keyfetch

### ISSUE THREAD

**Issue by tthoma24** [nathan-v/aws_okta_keyman#78]
**Is your feature request related to a problem? Please describe.**
the name "keyman" isn't gender inclusive

**Describe the solution you'd like**
Make the name gender-neutral

**Describe alternatives you've considered**
Rename the tool something like aws_okta_keyfetch

**Comment by nathan-v** [comment]
Keyman is a shortening of _key manager_. It's not gendered. :)
