### ISSUE TITLE
International company uses okta-emea base url.

### ISSUE THREAD

**Issue by coingraham** [nathan-v/aws_okta_keyman#82]
**Describe the bug**
My company is international, the base url for okta is "okta-emea.com" so logins fail.

**To Reproduce**
1. Have an international company that uses Okta based out of emea or a company that uses a custom URL
2. Try to login

**Expected behavior**
Application should have optional base urls that include okta-emea, custom, etc.

**Additional context**
Easy Fix: let me pass in the full URL as a configuration option.  Would you accept a PR that does this?

**Comment by nathan-v** [comment]
> Would you accept a PR that does this?

Yes, but it would need to support the previous configuration also. Maybe have it check for a . in the field and use the full field if it's present and just the field as a subdomain if not?

**Comment by nathan-v** [comment]
Dup of #65 but we'll keep this open also for now.

**Comment by nathan-v** [comment]
This will be fixed in the next update.

**Comment by nathan-v** [comment]
Done in #98.
